// <auto-generated />
namespace oficina_do_marcio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MudancaDataCadastro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudancaDataCadastro));
        
        string IMigrationMetadata.Id
        {
            get { return "202111282324004_MudancaDataCadastro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
